name: Bug
on:
  push:
  workflow_dispatch:
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "${{ hashFiles('**/hashme.txt') }}"
      - run: echo "${{ hashFiles('**/hashme.txt') }}"
      - run: echo "${{ hashFiles('**/hashme.txt') }}"
      - run: echo "${{ hashFiles('**/hashme.txt') }}"
      - run: echo "${{ hashFiles('**/hashme.txt') }}"
